# This is a basic workflow to help you get started with Actions

name: os-window-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_call

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install monorepo
        run: yarn

      - name: Lint
        run: yarn nx lint-all os-window-pages
